#!/usr/local/bin/perl -w

use strict;
use LWP::Simple;

my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
$mon = $mon+1; $year = $year - 100;
if ($mon < 10) { $mon = "0" . $mon; }
if ($mday < 10) { $mday = "0" . $mday; }
if ($hour < 10) { $hour = "0" . $hour; }
if ($min < 10) { $min = "0" . $min; }
if ($sec < 10) { $sec = "0" . $sec; }
my $currentdate = "${year}${mon}${mday}_${hour}${min}${sec}";

my $htmlgraphdate = "${mon}${mday}$year";

########################################################################
# Parse date files and update summary data file
######### ###############################################################
open(INPUT, "<input.txt");

my %ids;
my %values;
my %counts;
my $total;
my $threecount;
my @letters;
my @test;

foreach(<INPUT>) {

	my $flag2 = 0;
	my $flag3 = 0;
	undef %counts;
	chomp;
	my $id = $_;
	@letters = split(/,/, $id);
}


my $found = 0;
my $noun = 12;
my $verb = 2;
while (!$found) {

	@test = ();

	my $idx = 0;
	foreach my $val (@letters) {
		$test[$idx] = $letters[$idx];
		$idx++;
	}

	$test[1] = $test[$noun];
	$test[2] = $test[$verb];

	my $loc=0;
	my $res;
	while($test[$loc] != 99) {
		my $a = $test[$loc];
		my $b = $test[$loc+1];
		my $c = $test[$loc+2];
		my $d = $test[$loc+3];


		#		print "$a $b $c $d\n";
		#		print " $d  = testletters[$b] ";

		if ($a == 1) { $res = $test[$b] + $test[$c]; }
		if ($a == 2) { $res = $test[$b] * $test[$c]; }
		
		#                 print "$test[$c] ; ==  $res\n";


                $test[$d] = $res;



		$loc +=4;
	}	

	if ($test[0] == 4138687) {$found = 1;} 
print "$noun $verb $test[0]\n";

	$noun++;
	if ($noun == 100) { 
	        $verb++;
		if ($verb == 100) {exit;}
		$noun=0;
		$verb = 0 if ($verb == 100);
	}




  }


print "checksum = $letters[0]\n";

sub fuel {
	my $mass = shift;

	my $fuel = int($mass/3) - 2;

	print "$mass $fuel \n";

	return $fuel;
}

#foreach my $cnt1 (keys %ids) {
#  foreach my $cnt2 (keys %ids) {
#
#	  my $idx = 0;
#	  my $diff_cnt = 0;
#
#	  while ($idx < scalar @{$ids{$cnt1}}) { 
#		  my @arr1 = @{$ids{$cnt1}};
#                  my @arr2 = @{$ids{$cnt2}};
#            $diff_cnt++ if ($arr1[$idx] ne $arr2[$idx]);
#	    $idx++;
#          }
#
#	  if ($diff_cnt == 1) {
#	    print "$cnt1 @{$ids{$cnt1}} \n";
#            print "$cnt2 @{$ids{$cnt2}} \n";
#          }
#  }
#
#}


